version: 2.4.0
name: Leetcode
options:
  deploymentTarget:
      macOS: 10.14
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.Leetcode
settingGroups:
  common:
    INFOPLIST_FILE: "$(TARGET_NAME)/Info.plist"
    SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'
    SWIFT_VERSION: '5.1'
targets:
  Example:
    type: tool
    sources:
    - Sources/
    platform: macOS
    postbuildScripts:
    - script: swiftformat .
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        VERSIONING_SYSTEM: apple-generic
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
