version: 2.18.0
name: Leetcode

options:
  tabWidth: 2
  indentWidth: 2
  deploymentTarget:
      macOS: 10.14
  createIntermediateGroups: true
  bundleIdPrefix: com.mttcrsp.Leetcode
settingGroups:
  common:
    SWIFT_TREAT_WARNINGS_AS_ERRORS: 'YES'

targets:
  Leetcode:
    platform: macOS
    type: framework
    sources:
    - Sources/
    scheme:
      testTargets:
        - Tests
    postbuildScripts:
    - script: swiftformat .

  Tests:
    platform: macOS
    type: bundle.unit-test
    sources:
    - Tests
    dependencies:
    - target: Leetcode
    postbuildScripts:
    - script: swiftformat .
