name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    - name: Run tests
      run: swift test
