
name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: Run tests
      run: swift test
